### ISSUE TITLE
Cant change time

### ISSUE THREAD

**Issue by poopoopeepeepoopurine** [jaeheonshim/quizlet-match-hack#5]
Im prying to change the time to 10.6 so i put it at 10600 but it keeps going past the value...

**Comment by jaeheonshim** [comment]
This code works on my machine:
`document.getElementsByClassName("UIButton UIButton--hero")[0].click();
setTimeout(function(){for(var F = setTimeout(";"), i = 0; i < F; i++) clearTimeout(i)}, 10650); //Change 5100`
